gpu_id: 2
lr: 1e-3
cv_dir: weight
save_name: exp3
batch_size: 60
step_batch_size: 100
img_size: 128
epoch_step: 20
max_epochs: opt.epochs
num_workers: 0
parallel: False
alpha: 0.8
beta: 0.1
sigma: 0.5
load:
split: 4